// This file is generated by Slice Machine. Update with care!

import ContinentInfo from './ContinentInfo';
import ContinentPage from './ContinentPage';

export {
	ContinentInfo,
	ContinentPage,
};

export const components = {
	continent_info: ContinentInfo,
	continent_page: ContinentPage,
};
